import type { NormalizedMatch } from "@/lib/types";

export const demoMatches: NormalizedMatch[] = [
  {
    id: "demo-mex-rsa-2026",
    status: "upcoming",
    statusLabel: "À venir",
    minute: null,
    homeTeam: { name: "Mexique", code: "MEX" },
    awayTeam: { name: "Afrique du Sud", code: "RSA" },
    score: { home: null, away: null },
    kickoff: "2026-06-11T19:00:00.000Z",
    group: "Groupe A",
    venue: "Estadio Azteca",
    city: "Mexico",
  },
  {
    id: "demo-kor-cze-2026",
    status: "upcoming",
    statusLabel: "À venir",
    minute: null,
    homeTeam: { name: "Corée du Sud", code: "KOR" },
    awayTeam: { name: "Tchéquie", code: "CZE" },
    score: { home: null, away: null },
    kickoff: "2026-06-12T01:00:00.000Z",
    group: "Groupe A",
    venue: "Estadio Guadalajara",
    city: "Guadalajara",
  },
  {
    id: "demo-can-bih-2026",
    status: "upcoming",
    statusLabel: "À venir",
    minute: null,
    homeTeam: { name: "Canada", code: "CAN" },
    awayTeam: { name: "Bosnie-Herzégovine", code: "BIH" },
    score: { home: null, away: null },
    kickoff: "2026-06-12T22:00:00.000Z",
    group: "Groupe B",
    venue: "BMO Field",
    city: "Toronto",
  },
  {
    id: "demo-usa-par-2026",
    status: "upcoming",
    statusLabel: "À venir",
    minute: null,
    homeTeam: { name: "États-Unis", code: "USA" },
    awayTeam: { name: "Paraguay", code: "PAR" },
    score: { home: null, away: null },
    kickoff: "2026-06-13T01:00:00.000Z",
    group: "Groupe D",
    venue: "SoFi Stadium",
    city: "Los Angeles",
  },
];
